name: Build Android APK

on:
  workflow_dispatch:
    inputs:
      appName:
        description: 'App Name'
        required: true
        default: 'WebToApp'
      appPackage:
        description: 'App Package'
        required: true
        default: 'com.example.webtoapp'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed for creating a release

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Apply App Configuration
        run: node WebToApp/apply_config.js

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x ./WebToApp/gradlew

      - name: Build with Gradle
        run: ./gradlew assembleDebug --stacktrace
        working-directory: ./WebToApp

      - name: Rename APK
        run: |
          mv WebToApp/app/build/outputs/apk/debug/app-debug.apk "WebToApp/app/build/outputs/apk/debug/${{ github.event.inputs.appName }}.apk"

      - name: Create Release and Upload APK
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v-${{ github.run_number }}"
          name: "Build #${{ github.run_number }} - ${{ github.event.inputs.appName }}"
          files: "WebToApp/app/build/outputs/apk/debug/${{ github.event.inputs.appName }}.apk"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
